### ISSUE TITLE
New file should open empty "untitled" file not save dialog

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#103]
I think the behaviour is to aggressive with an popup.

An empty buffer would be better in my opinion.

**Comment by eidheim** [comment]
Actually I disagree here, three reasons:
* New file and new folder would behave differently (new folder: create new folder, new file: do not create new file yet)
* Currently you instantly see where your new file is in the directory tree, since its highlighted, which is nice
* You will now get an error message if you cannot write to the new file instantly, instead after editing your file, and then see the problems on save.
