### ISSUE TITLE
Question: Reach TextViews from singletons?

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#105]
Currently I'm doing it like this:
```c++
// get offset of cursor in textview
      [](){
        auto g_application = g_application_get_default();
        auto gio_application = Glib::wrap(g_application, true);
        auto application = Glib::RefPtr<Application>::cast_static(gio_application);
        if (application) {
          auto view = application->window->notebook.get_current_view();
          if (view != nullptr) {
            return view->get_source_buffer()->get_insert()->get_iter().get_offset();
          }
        }
        return -1;       
      },
```
any better way? @eidheim

**Comment by eidheim** [comment]
I think maybe the singleton class might have been a mistake. The reason being compile times and unnecessary includes which makes parsing while developing juci in juci slower too. 

Instead of the singleton classes we could implement a static function ::get in each of the singleton classes (terminal, menu and so on, and then also include both window and notebook as singletons with their own ::get functions. I can make these changes Tomorrow and push it to a separate branch (new_singleton_impl) for instance. It should not take long with search and replace (and maybe a regex or two), but I have to test the lazy initialisation stuff and get that right. This will lead to some ugly conflicts with your branch, but in the end the results will be better. I'll prioritise this and finish it Tomorrow. Luckily C++11 makes the whole thing easier as I understand it. Will also go through the includes and fix them so that we have no unnecessary includes (and as a result juci will compile and parse abit faster). 

Sorry for not realising this earlier.

**Comment by zalox** [comment]
I totally agree, this approach would make things a lot easier, I'm also kind of embarrassed I haven't noticed this as well.

The plugin module is moving along nicely. Compiles and runs in msys, arch and debian testing. If you don't mind, base this branch on mine so I wont have any conflicts after you re-factored. The python module shouldn't create any infringements if the plugins directory in juci home is empty. Also it shouldn't affect the rest of juci if disabled.

**Comment by eidheim** [comment]
I think I have to do the refactor based on the master branch sadly, since I know that one inside out, and in that way would avoid breaking things (most likely). But I think the number of conflicts will not be that bad. Mostly in menu.* I guess, without having studied your PR all that much. In your new files, just do a replace of "Singleton::menu()->" to "Menu::get()." for instance and you will be fine.

**Comment by eidheim** [comment]
Also, it will then be easier for me to go through your PR when that day comes:)

**Comment by eidheim** [comment]
Since I would not need to see the singleton changes also when comparing your PR with the master branch.

**Comment by zalox** [comment]
Since I keep merging with master github filters the commits already merged with master, but I realise now that I could just merge in master straight after it gets merged with master, I would only have conflicts in menu.cc so no worries.
