### ISSUE TITLE
platform native gui?

### ISSUE THREAD

**Issue by pebble2015** [cppit/jucipp#127]
Do you have any plan to make platform native GUI?
I don't quite like the GTK's looking at windows or os x.
Or may be you can consider to make GUI part be optional,
I mean may others could implement the windows and os x GUI without change the core part of sources.
Anyway, thanks for your work.

**Comment by eidheim** [comment]
We tried for instance using win32 dialogs to open files/directories, but there are issues like no way to create a directory (we had to use gtk dialogs for this). Eventually, at least for the 1.0.0 version, we had to use gtk dialogs, because of a missing win32 function in MSYS2 (https://github.com/cppit/jucipp/blob/master/src/CMakeLists.txt#L94). 

The code base gets large fast when supporting the various other native GUI elements, and you might find other issues like the above, which makes it even harder. Gtkmm might not be 100% perfect, but it is maybe the only alternative for a modern C++ gui (there are other projects like nana and sfmlgui, but my impression is that these are not as stable and feature full as gtk is), and have most if not all the needed functionality. There are places we use Gtk+ instead, but these cases are very few. 

Thus, in order to keep the code base in the project small (and relatively easy for others to contribute), and programmed in modern C++, I think the best choice would be to have the tight integration with gtkmm, at least until a better alternative is revealed. As a side note, I've heard Lyx tried to support various gui libraries, but decided against it in the end, and only now support Qt (correct me if I'm wrong). 

However, Gtk supports native menus for instance, and is using the native render engive on OS X, and Windows (if I am not mistaken).
