### ISSUE TITLE
Ninja build tool

### ISSUE THREAD

**Issue by tylorr** [cppit/jucipp#155]
I get this error while opening a project that uses cmake and ninja
```
CMake Error: Error: generator : MSYS Makefiles
Does not match the generator used previously: Ninja
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```
Does jucipp support using ninja?

**Comment by eidheim** [comment]
Could you post a link to that project so I could test it? Never tried ninja but it should work. I take it you also use juCi++ in MSYS2?

If the project has CMakeCache.txt in the root folder (in-source-build), cmake will fail if it tries to create a out-of-source build in for instance the ./build directory. The solution then is to remove the CMakeCache.txt. You could try do the cmake commands in terminal and see if you get the same error message. In preferences you have the following options that control the build (showing MSYS2 default preferences):
```json
    "project": {
        "default_build_path_comment": "Use <project_directory_name> to insert the project top level directory name",
        "default_build_path": "./build",
        "cmake_command": "cmake -G\"MSYS Makefiles\" -DCMAKE_INSTALL_PREFIX=C:/msys64/mingw64",
        "make_command": "cmake --build .",
        "debug_build_path_comment": "Use <project_directory_name> to insert the project top level directory name, and <default_build_path> to insert your default_build_path setting.",
        "debug_build_path": "<default_build_path>/debug"
    }
```
And this is equivalent to doing the following in the terminal from the project folder when opening the project for the first time:
```sh
mkdir build
cd build
cmake -G\"MSYS Makefiles\" -DCMAKE_INSTALL_PREFIX=C:/msys64/mingw64 ..
```

The make_command "cmake --build ." was used instead of "make" to support Ninja btw in a commit a month or two back.

**Comment by eidheim** [comment]
My guess is that the project already has a ./build directory, and `cmake -G"Ninja" ..` was used to generate the build there. If you want to always use ninja instead of MSYS Makefiles though, replace MSYS Makefiles with Ninja in the cmake_command. Sadly, one has to specify a build in MSYS2, since the default build will not work. Other platforms does not have this problem.

**Comment by tylorr** [comment]
Here's a link to the project: https://github.com/tylorr/knight-engine

> My guess is that the project already has a ./build directory, and cmake -G"Ninja" .. was used to generate the build there.
That's correct

I'll try out your suggestions when I get a chance.

**Comment by eidheim** [comment]
In general, you would not use other users build as it, for instance, contains absolute paths to the various files and executables. If you remove the build directory before opening the project/a file in juCi++, the issue should be resolved.

**Comment by eidheim** [comment]
Saw now that it was probably your build directory already, if you want to use Ninja instead update the cmake_command in preferences and you can most likely open the project without deleting your build directory.

**Comment by tylorr** [comment]
Changing cmake_command to use Ninja did the trick, thanks
