### ISSUE TITLE
why emulating tabs with gtk button?

### ISSUE THREAD

**Issue by agauniyal** [cppit/jucipp#161]
This would differ with different theme styles, tabs aren't buttons and look ugly on many themes :/ On my system they look quite big and embossed out, not exactly how tabs would look. I looked over here : https://developer.gnome.org/gtk3/stable/GtkNotebook.html and the default style is better than the button style.

And another small question, why using `Gtk::ReliefStyle::RELIEF_NONE` instead of `Gtk::ReliefStyle::RELIEF_NORMAL` 

And link provided in source code is broken for me:

```
//Based on http://www.micahcarrick.com/gtk-notebook-tabs-with-close-button.html
  std::string data =  ".button {\n"
                      "-GtkButton-default-border : 0px;\n"
                      "-GtkButton-default-outside-border : 0px;\n"
                      "-GtkButton-inner-border: 0px;\n"
                      "-GtkWidget-focus-line-width : 0px;\n"
                      "-GtkWidget-focus-padding : 0px;\n"
                      "padding: 0px;\n"
                      "}";
```

**Comment by eidheim** [comment]
The tab is made up of Gtk::Box containing a label and a button. This was done since the standard Gtk::Notebook tabs does not include a close button. Tested the tab visualisation on several platforms, and the current code was the best way I found to keep the tabs as small as possible. If you know of a better way to do this feel free to make a pull request, and I can test it on older Linux system as well as OS X and Windows. 

Gtk::ReliefStyle::RELIEF_NONE was added to make the close button as small as possible on older systems like Ubuntu 14 if I remember correctly. 

http://www.micahcarrick.com/gtk-notebook-tabs-with-close-button.html is not working for me either anymore, but I guess you can use a web page buffer service to view the older version. 

What platform are you using?

**Comment by agauniyal** [comment]
@eidheim arch linux (lldb disabled) with vertex theme - https://github.com/horst3180/vertex-theme/.

**Comment by eidheim** [comment]
Would you mind post a screenshot of juCi++ with this theme showing the tabs?

**Comment by eidheim** [comment]
I tried Vertex Theme on Debian testing and did not see anything strange with the tabs using this theme (tried both light and dark).

**Comment by agauniyal** [comment]
Yup here is the screenshot 
![2016-02-06-221911_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/12867893/e4bacbb6-cd1f-11e5-86e8-ee834dbfb419.png)

Gedit for comparision.

**Comment by eidheim** [comment]
Aha, I know what it is. juCi++ sets the theme in preferences (control-comma). You can change gtk_theme.name and variant there, as well as source.style (choose from your installed styles, although the juci styles might work best: juci-light, juci-dark and juci-dark-blue (see comments).

**Comment by agauniyal** [comment]
@eidheim I had already changed the theme and in previous screenshot both apps are using same theme. I digged around and found out some properties to play with. Here's an unfinished version :smile: 

![2016-02-06-230934_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/12868162/d1990ee2-cd26-11e5-946f-ab3166db06b2.png)

**Comment by eidheim** [comment]
I misunderstood, see now what you mean. Agree that the screenshot above is looking much better. Remember that the tabs got a bit more ugly when I added the possibility to move the tabs around. Looking forward to a PR making the tabs more pretty:)

**Comment by eidheim** [comment]
Solved I think in https://github.com/eidheim/jucipp/commit/75cc29def5f9095bdadc04ad727a46279e264921

**Comment by agauniyal** [comment]
Glad to see these changes :smile: would you mind updating ( or placing a new screenshot) with more than 1 tabs?
