### ISSUE TITLE
Add unit tests to help promote contributions

### ISSUE THREAD

**Issue by ElFeesho** [cppit/jucipp#198]
As someone who would like to help develop and use this IDE, I would like to know that any contribution I make had not broken the application in any way.

Although there are other ways to ensure this, unit tests offer a universal way for anyone to confirm that the application is working to the specification defined by the unit tests.

Naturally, poor coverage of the code base would mean that there would still be a lack of confidence that changes have not broken the application, but having a starting point might help bring more contributed unit tests to help broaden the confidence.

Please consider making this a higher priority than new features. 

Apologies if the description comes off as condescending, I did not intend for that to be the case.

**Comment by milleniumbug** [comment]
I really like this suggestion, as my very recent experience with unit tests was positive and helped me refactor code really easily, and made catching bugs a breeze.

There are several issues which have to be faced, for example:
- how do you unit test the GUI application?
- singleton removal (I've tried doing this in my [`singleton_removal` branch](https://github.com/milleniumbug/jucipp/commits/singleton_elimination), but without much success
- general modularization

I don't say this isn't possible to do, I'm just not that experienced in these areas.

**Comment by eidheim** [comment]
I am not sure if adding unit tests to GUI specific code is beneficial. However, there are some non-GUI classes that could be tested through unit tests. The CMake parser is a good example on this. 

However, feel free to contribute either way. Lately, several contributors have been looking through every pull request before merge, and this has been a great help keeping the source stable. Testing the changes on multiple platforms also helps.

**Comment by zalox** [comment]
I've been thinking about at least adding unit tests for a while now. I agree with @eidheim in focusing on non-event-driven components such as cmake, config and more.

In libclangmm we are using the boost test framework and I suppose we can use it here as well, but I'd like to discuss [google test](https://github.com/google/googletest) since it also supports mocking. To do mocking with boost people suggest to use google mock or [turtle ](http://turtle.sourceforge.net/). I think it would be cleaner to just use google test for everything.

**Comment by eidheim** [comment]
I'm actually leaning towards no test framework at all. Mocking our singletons is simple anyway, just create for instance info_mock.cc with the methods empty/returning some default value, and compile with these sources when building the tests. These mock implementations can be reused in all the tests as well.

The function assert from standard c++'s cassert is lacking however, but I guess one can create a similar macro and additionally include for instance the test's name. 

An example test with no framework: https://github.com/google/boringssl/blob/master/crypto/base64/base64_test.cc, but I would try to simplify it further.

**Comment by eidheim** [comment]
Also, to test private methods, add `-fno-access-control` to CXX flags when compiling the test.

**Comment by milleniumbug** [comment]
That sounds less like "We need to avoid unit testing frameworks", but more "We have had bad experiences with Boost.Test".

**Comment by eidheim** [comment]
My guess is that google test has similar issues as boost:
```c++
TEST(test_case_name, test_name) {
 ... test body ...
}
```
g_assert is part of the [Glib testing framework](https://developer.gnome.org/glib/stable/glib-Testing.html), so you are right, this framework is ok since it does not require us to write the tests in a specific manner. 
glibmm also uses the Glib testing framework for its tests.

We will never be required to use mocking combined with a dependency injection framework, and its enforcement of interfaces, in C++ for testing purposes, as long as our code is somewhat modular and we can create fake/stub implementations for test builds. This simplifies things a lot, and thus there is no need for a larger, maybe more complete, testing framework. If this was a Java project, however, interfaces, dependency injection, and mocking would have been required.

**Comment by eidheim** [comment]
As an example, I created tests/cmake_test.cc just to give it a try:
```c++
#include "cmake.h"
#include <glib.h>
#include <boost/filesystem.hpp>

int main() {
  CMake cmake(boost::filesystem::canonical("./tests"));
  
  g_assert(cmake.project_path.filename()=="jucipp");
  
  g_assert(cmake.get_executable(boost::filesystem::canonical("./tests/cmake_test.cc")).filename()=="cmake_test");
}
```
And created tests/terminal_stub.cc:
```c++
#include "terminal.h"

Terminal::Terminal() {}

int Terminal::process(const std::string &command, const boost::filesystem::path &path, bool use_pipes) {
  return 0;
}

size_t Terminal::print(const std::string &message, bool bold) {
  return 0;
}
```
One can turn off `ld` unused symbol errors by adding for instance `-flto` to the CXX flags, although there might be a better way. 

As an example, if the first assertion failed, I got:
```sh
**
ERROR:/Users/eidheim/test/jucipp/tests/cmake_test.cc:8:int main(): assertion failed: (cmake.project_path.filename()=="jucippp")
sh: line 1: 48743 Abort trap: 6           /Users/eidheim/test/jucipp/./build/tests/cmake_test
```
But there is also `g_assert_cmpstr` that will additionally show the contents of both strings as long as they are of type c-string.

**Comment by eidheim** [comment]
See #229

**Comment by eidheim** [comment]
See also #233

**Comment by eidheim** [comment]
Closing this for now as we have the most important tests in place.
