### ISSUE TITLE
window split (feature request)

### ISSUE THREAD

**Issue by milleniumbug** [cppit/jucipp#235]
![current](http://i.imgur.com/IyfIWYC.png)

I'd like to have two visible files at the same time because a.) often I want to see two files at the same time (either because I want to see header file and implementation file at the same time, or I want to look up a thing in a file, but I don't want to hide existing file because it's distracting, lots of reasons) b.) the amount of free space here is staggering.

Sadly, opening two instances of juCi++ is not a suitable replacement.

**Comment by eidheim** [comment]
Agree! Have thought about this many times, but have always dropped it due to the added complexity, especially when the parsing of a tab is triggered by saving another tab. But I think it's doable anyway. My suggestion is as follows when split window is triggered from menu:
* Add a notebook to the right with its own tabs (no tabs initially)
* Make it possible to drag and drop tabs between the two notebooks
* Open a new file in the notebook that currently has focus
* For simplicity, it should not be possible to have the same file opened in two notebooks
* Start reparsing, if needed, if the notebook tab gets focus, that is do not immediately start reparse a file even though it is shown on screen. 
* Current class Notebook will be renamed Notebooks, and some methods will be extended to support two notebooks. Most likely, the changes will only happen in this class. Notebooks::get_current_view for instance will return the view/tab with focus.
* `~/.juci/last_session.json` has to store information about which notebook the different files are opened in. 

I do not have time for this now, and I'd like to start working on git integration soon, but I think split window can be implemented during the summer. 

However, it would be great help if someone could create an as-simple-as-possible-one-file-example of two notebooks where it is possible to drag and drop tabs from one notebook to another.

**Comment by eidheim** [comment]
Actually, according to http://www.kksou.com/php-gtk2/sample-codes/move-tabs-between-two-notebooks-with-drag-and-drop.php and https://developer.gnome.org/gtkmm/stable/classGtk_1_1Notebook.html#a7b0555d623c2784dc45b5b3e6aa9c3e1, this seems much easier than I initially though. I'll fix it in a week or two.

**Comment by eidheim** [comment]
@milleniumbug see the PR above.
