### ISSUE TITLE
[Feature Request] Ninja Generator

### ISSUE THREAD

**Issue by NuLL3rr0r** [cppit/jucipp#255]
It would be great if juCi++ supports Ninja Generator as a target build system for CMake in addition to traditional make since Ninja is blazingly fast due to it's multi-threaded nature. In my estimation this is probably easy to implement since all cmake is needs is -GNinja parameter, e.g. `cmake -GNinja /some/path`. This will reduce builds time dramatically. On my system it's four times faster at least unless I pass -j5 to make to force it to use all CPU threads. I suppose there is no way to send arguments to make in juCi++, yet. So, it makes sense to add support for ninja. 

Ideas:
* Per project: When you open a CMakeLists.txt file inside Qt Creator for example, it has a combo box that let you choose between make and ninja as the target build system.
* Through config.json: Choosing either make or ninja globally

**Comment by eidheim** [comment]
To use ninja: open preferences, and change cmake_command to for instance `cmake -GNinja`. You might need to remove your already created builds after doing this change though.

**Comment by NuLL3rr0r** [comment]
Ops! I missed that. Thanks!

**Comment by eidheim** [comment]
No problem. Most implementations in juCi++ are quite simple and general. You can even set default build and debug build to the same path to always use debug build when running or debugging. Additionally, you can create your own build directory with the parameters you'd like, instead of letting juCi++ do that, and juCi++ will not touch your build files other than creating compile_commands.json in the default build path. Unlike perhaps many IDE's, juCi++ does not try to replace your OS and the capabilities of your terminal:)

**Comment by NuLL3rr0r** [comment]
Thanks for the tips. Behind that simplicity is more functionality one expects which is great actually. After a few hours of using it, I feel in love with it now. I'm an advocate now ;) Many thanks.
