### ISSUE TITLE
how to disable auto create main.cpp ?

### ISSUE THREAD

**Issue by sincoder** [cppit/jucipp#260]
when create a new project ,it auto create a main.cpp , but i do not need it , so i delete the main.cpp  ,bu  it will be auto create when build the project

**Comment by eidheim** [comment]
The new C++ project menu item is mostly for new users. Users more experienced with cmake would probably have their own cmake project template they use instead. 

If main.cpp is created when you build your project, it is because you have the deleted main.cpp open in a tab. Project files are by default saved when you compile, and thus the main.cpp file will be saved (created). The solution is to close the main.cpp tab after deleting the file.

**Comment by sincoder** [comment]
thanks for reply , but maybe auto close the tab when file been deleted will be make less confused。

**Comment by eidheim** [comment]
I decided not to close the tab on deletion, as this is common behaviour in other ide's (not closing tabs unless the user chooses to do so). One can for instance choose save as after deletion. Some people would also choose to use run command to delete a file, and the behaviour would be similar then, that is, the tab would not be closed.
