### ISSUE TITLE
Multicursor support

### ISSUE THREAD

**Issue by mdsitton** [cppit/jucipp#361]
Is there any plans to look into adding multiple cursor support like sublime text, atom, vs, and plenty of others support now days.

To me this is essential in a modern editor, the project is looking great so far and this is one of the larger missing things for me.

Thanks!

**Comment by eidheim** [comment]
Thank you for your input. I've never used multiple cursors, but going to add this on my TODO list:)

**Comment by eidheim** [comment]
I added multiple cursor support in https://github.com/eidheim/jucipp/commit/19afd6cce894ae8ccb3e3c191d1ffb28b1aab3b9

Keys are alt-up/down to add extra cursor, and alt-shift-up/down/left/right to move last added cursor.

Missing feature is home/end keys that are not yet moving all the cursors to correct line start/end if the indentation on the lines are different. 

There are probably other features missing too, since, like I said, I have never used multiple cursors before (been using regex-replace instead).

**Comment by eidheim** [comment]
I fixed the home/end keys when using multiple cursors.
