### ISSUE TITLE
Use autocompletion module from gtksourceviewmm instead.

### ISSUE THREAD

**Issue by zalox** [cppit/jucipp#4]

**Comment by eidheim** [comment]
The autocompletion module from gtksourceviewmm is pretty bad, at least I never got it to work well.
If you want to test it, see this: https://github.com/GNOME/gtksourceviewmm/blob/master/tests/completion/main.cc. You have to write class TestProvider : public Gsv::CompletionProvider, public Glib::Object at line 12 though instead of class TestProvider : public Glib::Object, public Gsv::CompletionProvider ....

**Comment by zalox** [comment]
So a better solution would be to write our own? If so, I would like to move the Source::View outside of juCi++ and make a library instead, or at least make it generic enough to just provide a vector or a map with suggestions.

**Comment by eidheim** [comment]
Your current completion solution seems better than the one supplied with gtksourceviewmm yes. I had the following problems with gtksourceviewmm:
* No search from key-input when the popup showed
* Popup got hidden after a key-input (if Completion::show was used instead of adding a provider)
* Crashes when changing a CompletionProvider's proposals

**Comment by zalox** [comment]
Then I suggest to create a popup module based on the one already implemented.

I suggest to make a generic popup which should be connected to the view that called it. 
subtypes can be 
* searchresultselector (in treeviews for instance)
* autocomplete (in sourceviews, terminal etc)

Each of them needs a provider which feeds the implementations with data.

**Comment by eidheim** [comment]
The provider way to do this seemed more complicated than this needs to be. But a generic popup would be nice, and one could for instance use it like this (without giving it too much thought though):
PopupSelector completions_selector(view, [this](std::string completion){
  //Perform action when a completion is selected (stored in the string)
});
//completions is a vector of possible completions for instance:
completions_selector.show(completions);
//And if esc is clicked:
completions_selector.hide();
Or something like it, as long as its simple and understandable. Of course here the PopupSelector must find the insert (cursor) in the view and place the popup accordingly. Never mind my naming of the class btw, you can probably find a better one.

**Comment by zalox** [comment]
I like the idea, however I would like to stick with my suggestion about a provider. I would like to be able to edit as much as possible before showing the data to the user. For instance different colours for members and functions etc.

popupselector:
 ```c++
void show(vector); // generates listview (for ease of use)
void show(listview); // listview which supports colours and icons etc
 ```
listview:
 ```c++
private:
    vector suggestions
    // + stuff for UI
 ```

**Comment by eidheim** [comment]
Sounds good!
