### ISSUE TITLE
Support other build tools than cmake

### ISSUE THREAD

**Issue by eidheim** [cppit/jucipp#97]
Create a layer on top of the current cmake class so that we can use projects like https://github.com/rizsotto/Bear to create compile_commands.json in the future.

**Comment by eidheim** [comment]
Also consider https://github.com/ARMmbed/yotta

**Comment by photex** [comment]
Perhaps http://bazel.io

**Comment by eidheim** [comment]
Interesting, I'll have a look

**Comment by guysherman** [comment]
waf https://github.com/waf-project/waf

**Comment by jaked122** [comment]
What sort of information is required to support additional project types? What information do I need to gather, is it just compile commands as they would be invoked through normal compilation? 

Or is there additional information that is helpful or desireable?

**Comment by guysherman** [comment]
I think, in its simplest form you need two things:

1. A way to specify the build / build and run / clean / debug commands
2. A way to specify include dirs / cflags / etc for your linting that runs through libclang

You could use something like "external-build.json" which stores those details, then in your get_language function, I think, you could look for that file or CmakeLists.txt, and choose a Project::CMake or a Project::External accordingly.

(You can tell I was looking through the code the other day thinking how I might do this)

**Comment by guysherman** [comment]
Yeah, I think that a quick-win would be to create a fairly open-ended option with essentially an <insert shell command here> approach for those that don't want to use CMake. But if you're looking at build systems, I recommend WAF, although processing the wscript from the ide could be tricky.

**Comment by jaked122** [comment]
It looks like it supports generating other sorts of buildfiles. 

I imagine that make might even end up on the list eventually. It certainly appears to be able to generate Visual studio project files, Eclipse project files, and XCode project files. 

Given that Visual Studio files aren't likely to have information useful for clang, and Eclipse and XCode are super into xml, it should be fairly simple. 

I haven't delved into that part of waf's codebase yet, so it may just add hooks to call waf to handle the building itself, if that is the case, then it's likely to be like pulling teeth.

I'm looking at the waf code right now, and it looks like it might be easiest to add a build step capture hook into the waf/Build.py build.execute_build method, as it appears to resolve the commands inside of it.

Having said that, it is a horrible, likely broken way to acheive the goal, also it'd require keeping an internal copy of waf's codebase to execute in place of it, and someone would have to make sure it doens't break every time that waf updates.

I think it might qualify as one of those bad design choices actually. Alternately, we could write a module to generate the build commands and output them instead of executing them, and see if they're willing to add it to the mainline waf repository to go out with the next release.

Or we could find the option to use `waf/waflib/extras/clang_completion_database.py`'s code, and just use that instead. That looks a lot easier to me.

**Comment by guysherman** [comment]
I think that is overcomplicating it, you should probably just go for a generic system, much the same as the way the clang_complete plugin for vim works.

**Comment by eidheim** [comment]
Thank you all for interesting input. 

Currently, what is needed from a build management system (like CMake) is a way to:
* create compile_commands.json for libclang (for C/C++ projects)
* find the root project path, for instance for saving the project files on compile and run
* getting a project name for the directory view
* figuring out an executable depending on project or current active file tab, for compile and run.

From my point of view, what would have been really great, would be a way to install dependencies directly from the build management system. I have seen attempts on this from sources, but what is needed in most cases I guess, is a way to use the native package system (apt-get for debian, pacman for Arch, homebrew for OS X and so on) to install these dependencies. However, I do not know of any build management system that is close to achieving this. CMake, at least, works around this issue helping us with the OS specific settings and searches for installed libraries. Is there a better build management system than CMake for coping with all the various platforms, libraries and compilers Today? Sorry, I have not studied waf yet. 

Either way, it should be possible to use other build management systems. Have tried to cleanup the current project/cmake source structure, but I failed miserably on the first try, hopefully the next one will be better:) @guysherman I share your opinion on how to do this in general. Hopefully, without creating a juCi++ specific project-file.

**Comment by jaked122** [comment]
Waf can actually do that directly.

**Comment by jaked122** [comment]
It generates a file called `compile_commands.json`.

That seems to be what we need for this

**Comment by guysherman** [comment]
But what exactly is compile_commands.json used for?
For instance if it is used to invoke the compiler, you don't need to bother, just invoke ./waf via a shell execute call.
If it is used to feed libclang for linting and completion, then all you really need is the superset of include dirs, and the cflags, as the linker side of things is irrelevant for those tasks.


Sent from Outlook on iOS




On Wed, Mar 2, 2016 at 4:34 PM -0800, "Alexander White" <notifications@github.com> wrote:












It generates a file called compile_commands.json.



That seems to be what we need for this

**Comment by eidheim** [comment]
I'm getting closer to a solution, where it will be easier to add support for other build management systems. It involves cleanup and simplification of the current cmake and project structure. Will probably take a week or two to implement, as I am a bit busy with work for the time being. Assigning myself though to this task for the time being.

**Comment by jaked122** [comment]
We need to know the compile commands to add smart autocompletion with
libclang.

**Comment by eidheim** [comment]
After merge of PR #168 implementations of other build management systems can be done in src/project_build.*. I'll leave this up to other developers that are interested in support for build systems other than CMake.
